version: 0.2

env:
  variables:
    s3_bucket: "simondownes.co.uk"
    hugo_version: "0.74.1"

phases:

  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt-get update
      - curl -L -o hugo.deb https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_extended_${hugo_version}_Linux-64bit.deb
      - dpkg -i hugo.deb

  pre_build:
    commands:
      - echo Current directory is $CODEBUILD_SRC_DIR
      - ls -la

  build:
    commands:
      - hugo -v
      - cd public && aws s3 sync . s3://${s3_bucket} --delete
