baseURL = 'https://docs.sierradelta.dev/'
languageCode = 'en-gb'
timeZone = "Europe/London"

# the basics
title = 'Simon Downes'
copyright = "Simon Downes"

# enable getting file metadata from git - e.g. last updated dates
# enableGitInfo = true

# ascii urls only
removePathAccents = true

[params]
description = "Welcome to the jungle!"

[permalinks]
  static = "/:filename/"

[taxonomies]
  tag = "tags"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

    [markup.highlight]
    style = 'perldoc'
